spring.data.mongodb.uri=mongodb+srv://ishu2004:ishu123D@parking-cluster.4cgzajr.mongodb.net/parkingdb?retryWrites=true&w=majority&appName=parking-cluster

spring.data.mongodb.database=parkingdb
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashodhaniishuwari@gmail.com
spring.mail.password=ishu2004@KU

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true